### ISSUE TITLE
TypeError: 'bool' object is not callable with Django 2.0.2 and Python 3.6

### ISSUE THREAD

**Issue by badeendjuh** [m7v8/django-basic-authentication-decorator#5]
Using Django 2.0.2 and Python3.6.4 the following error occurs when a request with the decorator is called.

> 
> Traceback (most recent call last):
>   File "/opt/exaboard/eXaboard/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
>     response = get_response(request)
>   File "/opt/exaboard/eXaboard/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/opt/exaboard/eXaboard/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/opt/exaboard/eXaboard/lib/python3.6/site-packages/django_basic_auth.py", line 81, in wrapper
>     realm, *args, **kwargs)
>   File "/opt/exaboard/eXaboard/lib/python3.6/site-packages/django_basic_auth.py", line 15, in view_or_basicauth
>     if test_func(request.user):
>   File "/opt/exaboard/eXaboard/lib/python3.6/site-packages/django_basic_auth.py", line 80, in <lambda>
>     lambda u: u.is_authenticated(),
> TypeError: 'bool' object is not callable

**Comment by badeendjuh** [comment]
Looks to be due to the is_authenticated() method having changed to an attribute per Django 2.0

https://docs.djangoproject.com/en/2.0/releases/1.10/#user-is-auth-anon-deprecation

**Comment by frankie-zeng** [comment]
remove the test_function

`def view_or_basicauth(view, request, realm = "", *args, **kwargs):
    """
    This is a helper function used by both 'logged_in_or_basicauth' and
    'has_perm_or_basicauth' that does the nitty of determining if they
    are already logged in or if they have provided proper http-authorization
    and returning the view if all goes well, otherwise responding with a 401.
    """
    if request.user.is_authenticated:
        # Already logged in, just return the view.
        #
        return view(request, *args, **kwargs)

    # They are not logged in. See if they provided login credentials
    #
    if 'HTTP_AUTHORIZATION' in request.META:
        auth = request.META['HTTP_AUTHORIZATION'].split()
        if len(auth) == 2:
            # NOTE: We are only support basic authentication for now.
            #
            if auth[0].lower() == "basic":
                uname, passwd = base64.b64decode(auth[1]).decode('utf-8').split(':', 1)
                user = authenticate(username=uname, password=passwd)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        request.user = user
                        if request.user.is_authenticated:
                            return view(request, *args, **kwargs)

    # Either they did not provide an authorization header or
    # something in the authorization attempt failed. Send a 401
    # back to them to ask them to authenticate.
    #
    response = HttpResponse()
    response.status_code = 401
    response['WWW-Authenticate'] = 'Basic realm="%s"' % realm
    return response
`
